version: '3'

services:
  sender:
    build:
      context: SenderService
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - redis-server
      - mysql
    volumes:
      - ./SenderService:/app
    networks:
      - mysqlnetwork
  recever:
    build:
      context: ReceiverService
    restart: unless-stopped
    depends_on:
      - redis-server
      - mysql
    volumes:
      - ./ReceverService:/app
    networks:
      - mysqlnetwork
  mysql:
    restart: always
    image: mariadb:10.7.3
    container_name: mariadb
    ports:
      - "3307:3306"
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    networks:
      - mysqlnetwork
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=local
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=root
  mysql-admin:
    restart: always
    image: phpmyadmin/phpmyadmin
    container_name: mariadb-phpmyadmin
    ports:
      - "8001:80"
    networks:
      - mysqlnetwork
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root

  redis-server:
    restart: always
    image: redis:6.2.6
    container_name: redis-server
    command: /bin/bash -c 'redis-server --appendonly yes'
    sysctls:
      - net.core.somaxconn=65535
    ports:
      - "6380:6379"
    volumes:
      - ./volumes/redis:/data
    networks:
      - mysqlnetwork
volumes:
  mysql:
    driver: local
  redis:
    driver: local

networks:
  mysqlnetwork:
    driver: bridge